FROM flink:1.20.1-scala_2.12-java17

USER root

# Cài JDK (có `include/` và `libjvm.so`)
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk python3 python3-pip build-essential && \
    ln -s /usr/bin/python3 /usr/bin/python

# Set lại JAVA_HOME nếu cần (có thể khác)
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64
ENV PATH=$JAVA_HOME/bin:$PATH

# Cài PyFlink
RUN pip install apache-flink==1.20.1 neo4j-driver networkx kafka-python